### ISSUE TITLE
Degree of truncated polynomials in tpb

### ISSUE THREAD

**Issue by sjbonner** [davidaarmstrong/psre#1]
Hi @davidaarmstrong! I'm teaching splines in one of my classes and was looking for a function to save me the work of calculating truncated polynomials for visualization. I found the tpb() function in your package, but noticed some behaviour I wasn't expecting. The degree of the truncated polynomials seems to be hardcoded to 3 and the degree argument only varies the non-truncated elements. 

Should the line 
`out <- cbind(out, (x - s[i])^3 * (x >= s[i]))`
be
`out <- cbind(out, (x - s[i])^degree * (x >= s[i]))`
instead?

Still saved me a lot of time. Thanks!

Simon

**Comment by davidaarmstrong** [comment]
Thanks, @sjbonner, for pointing out the big. I've fixed it in the most recent commit.
